### ISSUE TITLE
Only half the equipment works and I have all the needed mods downloaded 

### ISSUE THREAD

**Issue by Kleibx** [scfmod/FS22_DistributorSpecialization#1]
I have all the correct and up to date mods downloaded but only half the equipment will actually let me select stone ect with the command “z” unsure how to fix

**Comment by prestonw93** [comment]
same here

**Comment by scfmod** [comment]
That's weird, does the key bind for selecting input show up at all when you enter the machines (which is not working)?
Try with a clean savegame with only crushers and specialization mod enabled. If it's still not working create a pastebin entry with the log.txt, post the link here and I'll take a look at it.

**Comment by prestonw93** [comment]
yes key bind comes up and only 2 options for riversand an rubble.    im not sure what 
you mean by paste bin entry

**Comment by Kleibx** [comment]
I’ll take photos after work using the crushers on a new save for you

**Comment by scfmod** [comment]
https://pastebin.com/

Create a new paste (as they call it) with the contents of log.txt from FS22 :-) Then you will get a link to the contents you can share here.

Also, make sure you have the TP Materials for every map mod installed ("Construction Materials For Every Map"). Without this mod you won't be able to use the crushers as they require additional fill types not available in base game.

Some machines only have 2 options to select, this varies from machine to machine.

**Comment by Kleibx** [comment]
![Screenshot (1)](https://user-images.githubusercontent.com/128379565/226885722-95ff9e69-495c-4737-ba20-f01d8dbfd9d2.png)
![Screenshot (3)](https://user-images.githubusercontent.com/128379565/226885794-802588b8-7bef-4d0a-a168-1ddacb37fff1.png)
![Screenshot (4)](https://user-images.githubusercontent.com/128379565/226885833-f3037d02-fcba-4cd6-ba83-4bcd75c939c7.png)
![Screenshot (5)](https://user-images.githubusercontent.com/128379565/226885877-7a1d68d9-e769-44df-a00f-e5c64222754c.png)
![Screenshot (6)](https://user-images.githubusercontent.com/128379565/226885927-b99cea3c-fba3-47a6-a72f-d3d692bea5c2.png)
![Screenshot (7)](https://user-images.githubusercontent.com/128379565/226886001-4b16e949-1df5-4a67-b020-379d657fea4b.png)

**Comment by Kleibx** [comment]
![Screenshot (7)](https://user-images.githubusercontent.com/128379565/226886734-af823edf-a444-46e9-97de-400bca81ba7c.png)
![Screenshot (1)](https://user-images.githubusercontent.com/128379565/226886746-4bfd9dbd-1979-41f1-9951-670043333792.png)
![Screenshot (3)](https://user-images.githubusercontent.com/128379565/226886755-b3b2f44e-abc7-4ded-804e-27b1a4cf5b1d.png)
![Screenshot (4)](https://user-images.githubusercontent.com/128379565/226886770-8d5b3ac0-50f6-40da-8ba6-e0ad262e88e1.png)
![Screenshot (5)](https://user-images.githubusercontent.com/128379565/226886786-d2d1b7d5-5d89-4bc8-bdbf-e5491e48456f.png)
![Screenshot (6)](https://user-images.githubusercontent.com/128379565/226886798-d6bcb992-b5b5-4d02-b7e5-b7b630767a96.png)

**Comment by Kleibx** [comment]
FAAstnBvHM
https://pastebin.com/z61kKwYF

**Comment by scfmod** [comment]
Are you sure you have all the correct versions? I see that you have FS22_Terex_Finlay_Crusher_V3 which seems to be a older version or something?

The Distributor Specialization seems to work fine, so this is an issue with some of the machines being outdated

**Comment by scfmod** [comment]
You can observe what the specialization loads by looking for i.e:
```
[DistributorSpecialization] Info: Distributor processor loaded for vehicle: C 1540 Two Belts
```

There's no errors from the specialization

**Comment by Kleibx** [comment]
ill go through and remove the old ones but how come the mobicat dont work

**Comment by Kleibx** [comment]
ill re download fs miners screener pack

**Comment by prestonw93** [comment]
<script src="https://pastebin.com/embed_js/FA6xUeQZ"></script>

**Comment by prestonw93** [comment]
https://pastebin.com/FA6xUeQZ

**Comment by Kleibx** [comment]
hey mate, got it working thanks for the help, ive opened the game it its saying there is an update for it ??

**Comment by prestonw93** [comment]
> 

What did you do to get it to work ?

**Comment by prestonw93** [comment]
i still have no output crushed stone for the mobicat to the terex input screen

**Comment by scfmod** [comment]
Make sure you have downloaded the latest versions and that there is no mod conflicts, I can't help much without a log
