### ISSUE TITLE
Does this only work on crushers?

### ISSUE THREAD

**Issue by Bullitt33** [scfmod/FS22_DistributorSpecialization#4]
Just curious if this only works on crushers? Trying to implement this into a spray trailer to input water and pureherbicide to output herbicide.

Getting this error in the log.

 Error: Could not find specialization 'FS22_Demco_LTT42_Dash4_ManureSystem.FS22_DistributorSpecialization.distributor' for vehicle type 'FS22_Demco_LTT42_Dash4_ManureSystem.dash'.
 
 Any ideas or am I SOL?

**Comment by scfmod** [comment]
You're getting that error because you have not set up your vehicle type entry correctly :)
I just released a rework of this specialization, so I highly recommend migrating to use the new one instead: https://github.com/scfmod/FS22_MaterialProcessor

**Comment by scfmod** [comment]
> You're getting that error because you have not set up your vehicle type entry correctly :)

My bad, the issue is that because of mod .zip name it loads after yours in order, so one of the mods needs to be renamed in order to make the Distributor mod load before. (This is not an issue with the reworked version)
